import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Navbar } from "@/components/navbar";
import { Ripple } from "@/components/ui/ripple";
import ClickSpark from "@/components/ClickSpark";

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const jetBrainsMono = JetBrains_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${jetBrainsMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col relative overflow-hidden bg-background ">
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <ClickSpark
            sparkColor="#a78bfa"
            sparkSize={12}
            sparkRadius={25}
            sparkCount={12}
            duration={600}
            easing="ease-out"
            className="w-full min-h-full"
          >
            <div className="absolute inset-0 z-0 overflow-hidden pointer-events-none flex items-center justify-center opacity-60">
              <Ripple />
            </div>
            <div className="relative z-10 flex flex-col min-h-full w-full">
              <Navbar />
              {children}
            </div>
          </ClickSpark>
        </ThemeProvider>
      </body>
    </html>
  );
}
